apiVersion: v1
kind: Pod
metadata:
  name: mofed-test-pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-conf
spec:
  restartPolicy: OnFailure
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  containers:
  - image: mellanox/mlnx_ofed_linux-4.4-1.0.0.0-centos7.4
    name: mofed-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        rdma/vhca: 1
    command:
    - sh
    - -c
    - |
      ls -l /dev/infiniband /sys/class/net
      sleep 1000000
